env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/recommended'
]

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  ecmaVersion: 6
  sourceType: module
  project: './tsconfig.json'

parser: '@typescript-eslint/parser'

plugins: ['@typescript-eslint', 'react']

settings:
  'import/ignore': ['node_modules']
  react:
    version: '16'

rules:
  '@typescript-eslint/interface-name-prefix': [2, 'always']
  'react/prop-types': 0
  '@typescript-eslint/indent': ['error', 2]
    